services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    env_file:
      - ".env"
    volumes:
      - n8n-data:/home/node/.n8n
      - ./local-files:/files
    network_mode: service:n8n-on-vps
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    expose:
      - 5678
    environment:
      - TZ=America/Phoenix
      - GENERIC_TIMEZONE=America/Phoenix
      - N8N_RUNNERS_ENABLED=true
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - EXECUTIONS_MODE=queue
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      - N8N_ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - N8N_PROXY_HOPS=1
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      # Webhook URL for public access
      - WEBHOOK_URL=https://n8n.mydomain.com/
      - N8N_EDITOR_BASE_URL=https://n8n.mydomain.com/
    networks:
      - vps
    links:
      - postgres
      - redis

  n8n-on-vps:
    image: tailscale/tailscale:latest
    hostname: n8n-on-vps
    ports:
      - 5678:5678
    environment:
      - TS_EXTRA_ARGS=--auth-key file:/run/secrets/tsauthkey
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-n8n/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    secrets:
      - tsauthkey

secrets:
  tsauthkey:
    file: ~/.config/tsauthkey
