services:
  db:
    image: postgres:latest
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 512mb
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 536870912 # 512*2^20 bytes = 512Mb
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - vps-network

  pg-on-advin:
    image: tailscale/tailscale:latest
    hostname: pg-on-advin
    environment:
      - TS_EXTRA_ARGS=--auth-key file:/run/secrets/tsauthkey
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-n8n/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    secrets:
      - tsauthkey
    networks:
      - vps-network

secrets:
  tsauthkey:
    file: ~/.config/tsauthkey

networks:
  vps-network:
    name: vps-network
    external: true